version: '2'

services:
  elasticsearch:
    restart: unless-stopped
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk

  logstash:
    restart: unless-stopped
    build: logstash/
    command: -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

  kibana:
    restart: unless-stopped
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

  datadog:
    restart: unless-stopped
    build: datadog/
    environment:
      - API_KEY=$DD_API_KEY
      - DD_HOSTNAME=elk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge
